<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddAddressS</name>
   <tag></tag>
   <elementGuidId>03e43b40-1624-4311-80bc-ae754a0df969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-autocomplete-3&quot;]/mat-option[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-autocomplete-3&quot;]/mat-option[1]</value>
   </webElementProperties>
</WebElementEntity>
