<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddPhoneTypeS</name>
   <tag></tag>
   <elementGuidId>730e75c1-55f7-42fb-8c80-df140a3517d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;cdk-overlay-7&quot;]/div/div/mat-option[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;cdk-overlay-7&quot;]/div/div/mat-option[3]</value>
   </webElementProperties>
</WebElementEntity>
