<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddPhone</name>
   <tag></tag>
   <elementGuidId>c3e864db-937f-4fb8-bf36-12d377c5aed1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;form&quot;]/div[3]/div/div/div/mat-form-field[2]/div/div[1]/div[3]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form&quot;]/div[3]/div/div/div/mat-form-field[2]/div/div[1]/div[3]/div/input</value>
   </webElementProperties>
</WebElementEntity>
