import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable

WebUI.callTestCase(findTestCase('HeliumEdge_Login/HEL_001'), [:], FailureHandling.STOP_ON_FAILURE)
WebUI.delay(5)

WebUI.click(findTestObject('HeliumEdgeCCompany/Plus'))
WebUI.delay(3)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/Event'))
WebUI.delay(3)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/Other'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/Interview'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/Meeting'))
WebUI.delay(1)
WebUI.setText(findTestObject('Object Repository/HeliumEdgeCEvent/EventTitle'),'Arizona Event')
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTime'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeCancelButton'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTime'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeSelectDate'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeHourIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeHourIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeHourIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeHourIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeHourIncrease'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeHourDecrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeHourDecrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeHourDecrease'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeMinuteIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeMinuteIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeMinuteIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeMinuteIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeTimeMinuteIncrease'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeMinuteDecrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeMinuteDecrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeMinuteDecrease'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/StartDateandTimeSetButton'))
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/PersonalEvent'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/PersonalEvent'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDT'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTCancelButton'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDT'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTCalendarNextPage'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTDateSelect'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTHourIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTHourIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTHourIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTHourIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTHourIncrease'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTMinuteIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTMinuteIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTMinuteIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTMinuteIncrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTMinuteIncrease'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTHoursDecrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTHoursDecrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTHoursDecrease'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTMinuteDecrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTMinuteDecrease'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTMinuteDecrease'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EDTSetButton'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/TimeZone'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/TimeZoneSelect'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/AllDayEvent'))
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/AllDayEvent'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/Reminder'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/ReminderSelect'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/Repeat'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/RepeatSelect'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/CRCancel'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/Repeat'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/RepeatSelect'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/RepeatEvery'))
WebUI.setText(findTestObject('Object Repository/HeliumEdgeCEvent/RepeatEvery'),'')
WebUI.setText(findTestObject('Object Repository/HeliumEdgeCEvent/RepeatEvery'),'5')
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/RepeatEveryDuration'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/RepeatEveryDurationSelect'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/CRDone'))
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/HeliumEdgeCEvent/Location'),'Washington, Pennsylvania, Washington- 15301')
WebUI.doubleClick(findTestObject('Object Repository/HeliumEdgeCEvent/Description'))
WebUI.setText(findTestObject('Object Repository/HeliumEdgeCEvent/Description'),'This is a Description.....!')
WebUI.delay(1)
WebUI.setText(findTestObject('Object Repository/HeliumEdgeCEvent/LinkCompany'),'Malabar Fashion')
WebUI.delay(4)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/LinkCompanyS1'))
WebUI.delay(1)
WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/SaveandClose'))
WebUI.delay(1)







//----Stuck Code--------
//WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/LocationS'))
//WebUI.delay(1)

//WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EndsOn'))
//WebUI.delay(1)
//WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EonButton'))
//WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EonButton'))
//WebUI.delay(1)
//WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/EonDate'))
//WebUI.delay(1)

//WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/orgc'))
//WebUI.delay(1)
//WebUI.setText(findTestObject('Object Repository/HeliumEdgeCEvent/orginput'),'Bharat Patel')
//WebUI.delay(1)
//WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/orgselect'))
//WebUI.delay(1)
//WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/Attendes'))
//WebUI.delay(1)
//WebUI.setText(findTestObject('Object Repository/HeliumEdgeCEvent/AttendesI'),'Bharat Patel')
//WebUI.delay(1)
////WebUI.click(findTestObject('Object Repository/HeliumEdgeCEvent/AttendesS'))
////WebUI.delay(1)
