<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UploadFileC</name>
   <tag></tag>
   <elementGuidId>4663eed8-5693-4bc8-ad72-9aaac0cfe4d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[1]/div[2]/div[3]/div/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[1]/div[2]/div[3]/div/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
