<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AMPM</name>
   <tag></tag>
   <elementGuidId>ad866f17-1b52-471f-ac12-93fb3a0d007a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contactForm&quot;]/div/div[4]/div[3]/div[4]/he-time-picker/div/div/div[3]/mat-form-field/div/div[1]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contactForm&quot;]/div/div[4]/div[3]/div[4]/he-time-picker/div/div/div[3]/mat-form-field/div/div[1]/div[3]</value>
   </webElementProperties>
</WebElementEntity>
