<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Draft</name>
   <tag></tag>
   <elementGuidId>031a44fd-e5e7-4ccd-9427-aab963557dd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/he-contact-creation-page/div/div/mat-dialog-actions/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/he-contact-creation-page/div/div/mat-dialog-actions/button[1]</value>
   </webElementProperties>
</WebElementEntity>
