<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmailTypeSelect</name>
   <tag></tag>
   <elementGuidId>b8884a6c-5d83-4785-9739-7809cf1948c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;cdk-overlay-8&quot;]/div/div/mat-option[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;cdk-overlay-8&quot;]/div/div/mat-option[1]</value>
   </webElementProperties>
</WebElementEntity>
