<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmailType</name>
   <tag></tag>
   <elementGuidId>92714c2f-f04f-459f-a295-61e531c9ae0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;form&quot;]/div[2]/div/div/div/mat-form-field[2]/div/div[1]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form&quot;]/div[2]/div/div/div/mat-form-field[2]/div/div[1]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
