<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Extention</name>
   <tag></tag>
   <elementGuidId>4084a746-9679-44a2-8bbe-6ceaf1bef639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;form&quot;]/div[2]/div/div/div/mat-form-field[3]/div/div[1]/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form&quot;]/div[2]/div/div/div/mat-form-field[3]/div/div[1]/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>
