<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Facebook</name>
   <tag></tag>
   <elementGuidId>afa99572-5d57-4a52-97f7-d71533c4bfda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contactForm&quot;]/div/div[5]/div[2]/div[2]/he-textfield/div/form/div/mat-form-field/div/div[1]/div[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contactForm&quot;]/div/div[5]/div[2]/div[2]/he-textfield/div/form/div/mat-form-field/div/div[1]/div[4]/input</value>
   </webElementProperties>
</WebElementEntity>
