<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fax</name>
   <tag></tag>
   <elementGuidId>a4a08123-d985-4729-8f1f-232ee8857965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contactForm&quot;]/div/div[4]/div[3]/div[2]/he-textfield/div/form/div/mat-form-field/div/div[1]/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contactForm&quot;]/div/div[4]/div[3]/div[2]/he-textfield/div/form/div/mat-form-field/div/div[1]/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>
