<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pmc</name>
   <tag></tag>
   <elementGuidId>f82fce66-e3d8-424a-8180-c63652be9553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contactForm&quot;]/div/div[4]/div[3]/div[3]/he-select/div/form/div/mat-form-field/div/div[1]/div[3]/mat-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contactForm&quot;]/div/div[4]/div[3]/div[3]/he-select/div/form/div/mat-form-field/div/div[1]/div[3]/mat-select</value>
   </webElementProperties>
</WebElementEntity>
