<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendes</name>
   <tag></tag>
   <elementGuidId>256aadc4-9e7b-4e24-bbb9-c51c01d41133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-chip-list-1&quot;]/div/mat-chip/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-chip-list-1&quot;]/div/mat-chip/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
