<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CRCancel</name>
   <tag></tag>
   <elementGuidId>178f7e94-08cc-4bfd-aac6-855935134424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-1&quot;]/he-task-recurrence/div/div[2]/div/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-1&quot;]/he-task-recurrence/div/div[2]/div/div/button[1]</value>
   </webElementProperties>
</WebElementEntity>
