<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CRDone</name>
   <tag></tag>
   <elementGuidId>5fa4c94b-a267-4625-b5d8-3ed26399d3e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-2&quot;]/he-task-recurrence/div/div[2]/div/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-2&quot;]/he-task-recurrence/div/div[2]/div/div/button[2]</value>
   </webElementProperties>
</WebElementEntity>
