<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EDTCalendarNextPage</name>
   <tag></tag>
   <elementGuidId>26080734-1277-4021-bdea-737560585a68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;owl-dt-picker-1&quot;]/div[2]/owl-date-time-calendar/div[1]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;owl-dt-picker-1&quot;]/div[2]/owl-date-time-calendar/div[1]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
