<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EDTMinuteIncrease</name>
   <tag></tag>
   <elementGuidId>7c933658-0e3f-4282-abbf-22b3c778d47b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;owl-dt-picker-1&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;owl-dt-picker-1&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[2]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
