<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EonButton</name>
   <tag></tag>
   <elementGuidId>cb5ce64b-d2bf-4bf0-91d7-23cc412046d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-datepicker-1&quot;]/mat-calendar-header/div/div/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-datepicker-1&quot;]/mat-calendar-header/div/div/button[3]</value>
   </webElementProperties>
</WebElementEntity>
