<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EonDate</name>
   <tag></tag>
   <elementGuidId>6d3d2230-a5f2-4666-b4c0-c9753ef65514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-datepicker-1&quot;]/div/mat-month-view/table/tbody/tr[4]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-datepicker-1&quot;]/div/mat-month-view/table/tbody/tr[4]/td[4]</value>
   </webElementProperties>
</WebElementEntity>
