<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>orgc</name>
   <tag></tag>
   <elementGuidId>78256fb5-ff21-449c-8da8-fe7852552c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-chip-list-0&quot;]/div/mat-chip/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-chip-list-0&quot;]/div/mat-chip/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
