<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reminder</name>
   <tag></tag>
   <elementGuidId>1be331ea-7efa-4f2e-af83-30304c527b64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[5]/he-select[1]/div/form/div/mat-form-field/div/div[1]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[5]/he-select[1]/div/form/div/mat-form-field/div/div[1]/div[3]</value>
   </webElementProperties>
</WebElementEntity>
