<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Repeat</name>
   <tag></tag>
   <elementGuidId>3e6859fb-1d89-47be-bc7d-35abc7bd79b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[5]/he-select[2]/div/form/div/mat-form-field/div/div[1]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[5]/he-select[2]/div/form/div/mat-form-field/div/div[1]/div[3]</value>
   </webElementProperties>
</WebElementEntity>
