<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDateandTimeTimeMinuteIncrease</name>
   <tag></tag>
   <elementGuidId>f473bbc4-c0a0-40dd-be02-2ce5df6d225e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[2]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
