<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDateandTimeCancelButton</name>
   <tag></tag>
   <elementGuidId>0f22002f-bb1b-4e69-9be4-8028cdd9b095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/div/button[1]</value>
   </webElementProperties>
</WebElementEntity>
