<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDateandTimeTimeHourIncrease</name>
   <tag></tag>
   <elementGuidId>68551588-db38-4817-ae7e-8373501d9253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[1]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
