<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDateandTimeHourDecrease</name>
   <tag></tag>
   <elementGuidId>947368fb-f6ea-4007-9f45-5b867d4790d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[1]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[1]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
