<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDateandTimeSetButton</name>
   <tag></tag>
   <elementGuidId>3dbadf3b-4e85-4ae5-bed8-b0d332a15be5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/div/button[2]</value>
   </webElementProperties>
</WebElementEntity>
