<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDateandTime</name>
   <tag></tag>
   <elementGuidId>ec84ef14-95a7-4fd6-bd15-dfcc81fed4b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[3]/div[1]/mat-form-field/div/div[1]/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[3]/div[1]/mat-form-field/div/div[1]/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>
