<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDateandTimeMinuteDecrease</name>
   <tag></tag>
   <elementGuidId>313bcb8d-1f09-43d2-b115-d0c3c0f25c16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;owl-dt-picker-0&quot;]/div[2]/owl-date-time-timer/owl-date-time-timer-box[2]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
