<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimeZone</name>
   <tag></tag>
   <elementGuidId>55881a8d-221f-456d-be35-3e5350ffa765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[4]/he-select/div/form/div/mat-form-field/div/div[1]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/he-event-creation-page/div/mat-dialog-content/form/div[4]/he-select/div/form/div/mat-form-field/div/div[1]/div[3]</value>
   </webElementProperties>
</WebElementEntity>
