<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JobSettingButton</name>
   <tag></tag>
   <elementGuidId>f4fc70a4-ae7b-47ee-bed2-86b113e8e27a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/he-job-creation-page/div/div/div/div/div[1]/button[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/he-job-creation-page/div/div/div/div/div[1]/button[3]/span</value>
   </webElementProperties>
</WebElementEntity>
