<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CancelButton</name>
   <tag></tag>
   <elementGuidId>0d34b18a-1d8a-499b-aa93-c3c2c2d56022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-1&quot;]/he-dialog/div/mat-dialog-actions/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-1&quot;]/he-dialog/div/mat-dialog-actions/button[1]</value>
   </webElementProperties>
</WebElementEntity>
