<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Draft</name>
   <tag></tag>
   <elementGuidId>0ee54dd6-16c8-4c57-9292-3250eb2ec062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/he-job-creation-page/div/div/div/div/div[1]/button[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/he-job-creation-page/div/div/div/div/div[1]/button[1]/span</value>
   </webElementProperties>
</WebElementEntity>
