<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Availability</name>
   <tag></tag>
   <elementGuidId>a9d9da48-3910-4879-86f6-b7c30a2e274f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;candidateForm&quot;]/div/div[6]/he-select[3]/div/form/div/mat-form-field/div/div[1]/div[3]/mat-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;candidateForm&quot;]/div/div[6]/he-select[3]/div/form/div/mat-form-field/div/div[1]/div[3]/mat-select</value>
   </webElementProperties>
</WebElementEntity>
