<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BI</name>
   <tag></tag>
   <elementGuidId>64fe293a-293c-49bd-9788-090f380faa7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-0&quot;]/div/he-candidate-details-tab/div/div/div[1]/h3/button/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-0&quot;]/div/he-candidate-details-tab/div/div/div[1]/h3/button/span/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
