<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CandidateOwner</name>
   <tag></tag>
   <elementGuidId>49cafe33-f1ab-4bee-92e3-45c108097bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;candidateForm&quot;]/div/div[3]/he-autocomplete/div/form/div/mat-form-field/div/div[1]/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;candidateForm&quot;]/div/div[3]/he-autocomplete/div/form/div/mat-form-field/div/div[1]/div[3]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-9</value>
   </webElementProperties>
</WebElementEntity>
