<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CandidateOwnerS</name>
   <tag></tag>
   <elementGuidId>d4b4e46b-3e59-4783-aa57-05e9b28dc7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-autocomplete-2&quot;]/mat-option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-autocomplete-2&quot;]/mat-option</value>
   </webElementProperties>
</WebElementEntity>
