<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DImage</name>
   <tag></tag>
   <elementGuidId>9f0c6319-6b5c-47e1-aac3-e68bce76eac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;candidateForm&quot;]/div/div[1]/he-photo-upload/div/div/div/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;candidateForm&quot;]/div/div[1]/he-photo-upload/div/div/div/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
