<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ElS</name>
   <tag></tag>
   <elementGuidId>d1971b2c-c317-429f-bdd0-7a45bca3a31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;cdk-overlay-16&quot;]/div/div/mat-option[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;cdk-overlay-16&quot;]/div/div/mat-option[4]</value>
   </webElementProperties>
</WebElementEntity>
