<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Star</name>
   <tag></tag>
   <elementGuidId>f817fc99-d403-4405-9183-e2aa299cc425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/he-candidate-details-dialog/div[1]/div[1]/div/div[1]/div/div/h2/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/he-candidate-details-dialog/div[1]/div[1]/div/div[1]/div/div/h2/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
