<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Id filed find in chrome.</description>
   <name>Dashboard</name>
   <tag></tag>
   <elementGuidId>812959ef-94ba-4581-8056-dc6d588b10a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sideMenu&quot;]/div/button[1]/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Capa_1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sideMenu&quot;]/div/button[1]/span/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
